language: node_js
node_js:
  - "8"
  - "9"
  - "10"
install:
  - npm install -g codecov
script:
  - npm run lint
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success:
  - npm version patch
  - npm publish